spring:
  application:
    name: location-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/location_db
  #  cache:
  #    type: redis
  redis:
    host: redis
server:
  port: 8080